services:
  client:
    build:
      context: ..
      dockerfile: client/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    volumes:
      - ../client:/app/client
      - ../shared:/app/shared
      - /app/client/.next
      - /app/client/node_modules
      - /app/shared/node_modules
    command: pnpm dev
    env_file:
      - ../.env

  server:
    build:
      context: ..
      dockerfile: server/Dockerfile.dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      PORT: ${SERVER_PORT}
    volumes:
      - ../server/src:/app/server/src
      - ../shared:/app/shared
      - /app/server/node_modules
      - /app/shared/node_modules
    command: pnpm start:dev
    env_file:
      - ../.env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    env_file:
      - ../.env

volumes:
  postgres_data: 