version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    command: node server.js
    restart: always
    ports:
      - "3000:3000"

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - PORT=${SERVER_PORT}
    command: pnpm start:prod
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_prod_data: 