name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd client
          pnpm install

      - name: Build
        run: |
          cd client
          pnpm build

      - name: Delete remote .next directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 21098
          script: |
            echo "Deleting .next directory"
            rm -rf /home/woorapqt/apps/sunlah.com
            
      - name: Deploy project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 21098
          source: "client/package.json,client/pnpm-lock.yaml,client/ecosystem.config.js,client/.next/"
          target: "/home/woorapqt/apps/sunlah.com"
          strip_components: 1

      - name: Start PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 21098
          script: |
            cd /home/woorapqt/apps/sunlah.com
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm
            fi
            pnpm install
            if pm2 show sunlah > /dev/null; then
              pm2 reload ecosystem.config.js
            else
              pm2 start ecosystem.config.js
            fi 