name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd client
          pnpm install

      - name: Build
        run: |
          cd client
          pnpm build

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 21098
          source: "client/.next/,client/package.json,client/pnpm-lock.yaml,client/server.js,client/public/**"
          target: "/home/woorapqt/apps/sunlah.com"
          strip_components: 1
          overwrite: true

      - name: Install Dependencies on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 21098
          script: |
            cd /home/woorapqt/apps/sunlah.com
            
            # pnpm 전역 설치 확인
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm@10.7.1
            fi
            
            # 의존성 설치
            pnpm install --prod --no-frozen-lockfile